### ISSUE TITLE
Kind words from haiti project friends

### ISSUE THREAD

**Issue by noraj** [HashPals/Name-That-Hash#29]
Hi I saw you released Name-That-Hash a few days ago and opened an issue on https://github.com/psypanda/hashID/issues/50.

Congratz 👏🏻 there are some nice features like Popularity Ratings, Hash Summaries, Accessibility and the API + web app.

Just so you know I started a similar project in 2019: https://github.com/noraj/haiti. I coded haiti in ruby and added a few new features and improvements to hashID (see [here](https://noraj.github.io/haiti/#/why)).

I saw you moved [hashID prototypes.json](https://github.com/psypanda/hashID/blob/master/prototypes.json) database in pure python ([name_that_hash/hashes.py](https://github.com/HashPals/Name-That-Hash/blob/main/name_that_hash/hashes.py)).
I added a few more hashes when I started the project (haiti) so you can diff [hashID prototypes.json](https://github.com/psypanda/hashID/blob/master/prototypes.json) and [mine](https://github.com/noraj/haiti/blob/master/data/prototypes.json) to see what I added if you want to add them too in NTH.

You can also check the activity on [my database](https://github.com/noraj/haiti/commits/master/data/prototypes.json) because I'm adding new JtR references right now.

It's nice that you made your tool in python 🐍 and me did mine in ruby 💎 as we both made it a library first (before a CLI tool) so as it's not the same language it's helps having a nice lib in different languages.

Let me know if I can help with NTH or if you want to help me add features like Popularity Ratings in haiti. ❤️

**Comment by bee-san** [comment]
Hey Noraj!!! Nice one, Ruby is a great language 💎

We got rid of the JSON file as it wasn't really needed, and we changed the NamedTuples into DataClasses to support more modern features. 

This project grew because [Ciphey](https://github.com/ciphey/ciphey) needed a fast hash-cracking system, and our [Hash cracking system](https://github.com/HashPals/Search-That-Hash) required a hash identification tool, and all of these are in Python so we used Python.

Thankfully one of the core contributors to HashID bburky approved of the PR and submitted a PR 🥳  There's no way we could have built this tool without the groundwork set by psypanda and bburky  😄 

Also many thanks to @SkeletalDemise , @Jayy001 and @smokeme too for building out the website and submitting PRs :)))

Open source is so beautiful, you build something and other people help you make it better (and very often, they're smarter than you!)

This tool is really just an accumulation of the work of many other people that I'd forever be thankful for :D
