### ISSUE TITLE
Make an Arch User Repository AUR package

### ISSUE THREAD

**Issue by bee-san** [HashPals/Name-That-Hash#37]
Hey 👋

We're looking for someone to submit this project as an AUR package :D 

See:
https://wiki.archlinux.org/index.php/Python_package_guidelines

**Comment by bee-san** [comment]
> Hello there, I would be interested in tackling this issue. From what I've understood the concept is that I need to configure setup.py so that it can be built. But in packages/setup.py you state we shouldn't touch it as it's automatically generated. Should I not touch anything in the repo and just try to upload it as an AUR package, or do I need to change something in the configuration files of the project?
> 
> Thanks for your time

Hey!

Feel free to edit `setup.py` as much as you want, it only says not to touch it because it was auto-generated :) Whatever makes it easiest for you :D

**Comment by Ckrielle** [comment]
And just like that, it is done!

https://aur.archlinux.org/packages/python-name-that-hash

After some research it turned out all I had to do was write the PKGBUILD. Unfortunately if a dependency is only in the AUR, pacman can't find it to install it, which was a problem for loguru. The link you provided however gave a workaround, and I have the PKGBUILD manually install it with pip. I'm pretty sure it works fine, but if you have any requests like directories to change, feel free to contact me at the email provided on the PKGBUILD. Other than that I'll keep an eye out for changes to the repo and alter the PKGBUILD accordingly

**Comment by bee-san** [comment]
> And just like that, it is done!
> 
> https://aur.archlinux.org/packages/python-name-that-hash
> 
> After some research it turned out all I had to do was write the PKGBUILD. Unfortunately if a dependency is only in the AUR, pacman can't find it to install it, which was a problem for loguru. The link you provided however gave a workaround, and I have the PKGBUILD manually install it with pip. I'm pretty sure it works fine, but if you have any requests like directories to change, feel free to contact me at the email provided on the PKGBUILD. Other than that I'll keep an eye out for changes to the repo and alter the PKGBUILD accordingly

Thank you so much!!! I am considering switching from Loguru, it'll be in the release notes if I do :D
